### ISSUE TITLE
Text editor Block rendering

### ISSUE THREAD

**Issue by JDL747** [luyadev/luya#1029]
It's seems like there is CSS issues for the WYSWYG plugin of the Text editor Block.

Would be nice to have something like [redactor.js](https://imperavi.com/redactor/)

![screen shot 2016-10-13 at 02 41 07](https://cloud.githubusercontent.com/assets/3844254/19332702/d2946792-90ee-11e6-9e12-ce1259de134c.png)

**Comment by nadar** [comment]
We dont want to provide any WYSIWYG Editors anymore in future, as we have the concept of using blocks in order to structure the content. Otherwise the customer will end up in a messy html code with WYSIWYG Editors. Maybe we are going to implement a Markdown Editor which allows People to use a wysiwyg editor but it's producing markdown code instead of HTML.
