### ISSUE TITLE
How to create an autocomplete plugin in ngrest admin?

### ISSUE THREAD

**Issue by vuongminh** [luyadev/luya#1107]
Sorry to ask a question at here...

How can i create an autocomplete plugin with directive of angular like https://material.angularjs.org/latest/demo/autocomplete .At server side is no problem with me but at client side i don't know how to? Many thanks.

**Comment by nadar** [comment]
We have also made an Autocomplete Plugin you can provide your data from an array or model:

The Select Plugin with autocomplete: https://luya.io/guide/ngrest-plugin-select
All Plugins: https://luya.io/guide/ngrest-plugins

In order to write your own plugin you can follow this guide: 
https://luya.io/guide/ngrest-plugins#create-a-custom-project-plugin

Feel free to ask if you have any question or problem.

**Comment by vuongminh** [comment]
Thank you very much @nadar !

**Comment by nadar** [comment]
@vuongminh You are welcome. Just let me know if you need more help or informations.
