### ISSUE TITLE
Ukrain translation

### ISSUE THREAD

**Issue by ASYOU99** [luyadev/luya#1121]
### What steps will reproduce the problem?

I would like to translate the app into the Ukrainian language you need to do? just send you a file transfer, such as those in which Russian is written English and German yazykibb, namely - messages / ru / app.php

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
Hi @ASYOU99 this would be great!

Just create a folder with the Ukrain short code (its `ua` i guess), a translate from the file you like:

In order to translate the most important modules:

- [ ] https://github.com/luyadev/luya/tree/master/modules/admin/src/messages
- [ ] https://github.com/luyadev/luya/tree/master/modules/cms/src/frontend/messages
- [ ] https://github.com/luyadev/luya/tree/master/modules/cms/src/admin/messages
- [ ] https://github.com/luyadev/luya/tree/master/envs/kickstarter/messages

"Optional" modules which are not part of the default installation:

- [ ] https://github.com/luyadev/luya/tree/master/modules/crawler/src/admin/messages
- [ ] https://github.com/luyadev/luya/tree/master/modules/errorapi/src/messages
- [ ] https://github.com/luyadev/luya/tree/master/modules/news/src/admin/messages

Thank you for help us translating LUYA, if you have any questions, let us know.

**Comment by ASYOU99** [comment]
I made the first сomitt you saw him, he passed?

**Comment by nadar** [comment]
Looks good! After commiting all the important module translations you could send me a pull request. Thanks!

**Comment by nadar** [comment]
Thank you @ASYOU99 great work, hopefully some Ukraine people will enjoy your translations.

I will add a changelog entry and add the angular localizations files for Ukraine language.

**Comment by nadar** [comment]
https://github.com/luyadev/luya/pull/1123
