### ISSUE TITLE
New item form in module: dates wrong

### ISSUE THREAD

**Issue by neurobug** [luyadev/luya#1235]
### What steps will reproduce the problem?

Create module
Create model from table with fields type date or timestamp
import, set up permissions set up module, add menus for models

for the model with dates or timestamp, I go to add a new item in the admin panel, then I got a form with input fields to enter the data

### What is the expected result?

dates and timestamps shown properly
dates being saved properly

### What do you get instead? (A Screenshot can help us a lot!)

The original values were not loaded, instead I got an NaN

![screen shot 2017-03-14 at 8 16 16 pm](https://cloud.githubusercontent.com/assets/1685789/23929393/d1afb00c-08f3-11e7-8d65-982760af2ba9.png)

I selected in the empty fields a date value and then saved, I got the following error

![image](https://cloud.githubusercontent.com/assets/1685789/23929546/06574f1c-08f5-11e7-9156-6d520d213c35.png)

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 1.0.0-RC2
| PHP Version      | PHP 5.6.30
| Platform         | Apache
| Operating system | OSX

**Comment by nadar** [comment]
hi @neurobug So i think you where using the SQL Type "datetime"? We are always working with UNIX timestamps (so it should just be an integer value). But i think it would be good the date/datetime plugin can detected the field type and changes its value according whether its datetime or int (unix timestamp).

Summary:
+ To temporary fix your problem, change the field type to integer(11)
+ I will improve the date/datetime plugins in order to detect whether its should a datetime value or unix timestamp.
