### ISSUE TITLE
When you delete the images from the file manager they are not deleted from the storage

### ISSUE THREAD

**Issue by nandes2062** [luyadev/luya#1275]
### What steps will reproduce the problem?
When you delete the images from the file manager they are not deleted from the storage

### What is the expected result?
Completely remove an image from storage.

### What do you get instead? 
When you delete the image from the file manager, the 40px and 300px thumbnails, and the original image are not removed from storage

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | RC3
| PHP Version      | 7.0.15
| Platform         | Apache
| Operating system | Windows/Linux Server/OSX/etc.
Linux Server/OSX/etc.

**Comment by nadar** [comment]
hi @nandes2062 currently this is an **expected** behavior as we can not know where the filter version of the image is in use. So we can not just delete the image and its filters. If you have a good idea how to solve this problem, let me know.

**Comment by nandes2062** [comment]
Well thanks @nadar , I hope Luya solves this bug soon.

**Comment by nandes2062** [comment]
Just for now it occurs to me to use the synchronization command to synchronize the database and the files in the environment, so that the unused filters are deleted, am I correct?

**Comment by nadar** [comment]
@nandes2062 I don't understand what you are trying to say:

> Just for now it occurs to me to use the synchronization command to synchronize the database and the files in the environment, so that the unused filters are deleted, am I correct?

The `admin/proxy` command synchronize the full database and files which are not marked as deleted in the database.

As i said, its not actually a BUG, its an expected behavior. When you remove a file, the file will be marked as deleted and removed from the storage folder, but this is **not the case for applied image filters versions** (the ones which start with the filter number like `10_myimage.jpg`) as we don't know where they are used at this point.

**Comment by nadar** [comment]
dear @nandes2062 i am going to close this issue, in order to cleanup the issues. Its not an actuall bug, if you have any idears for improvments, please create a new issue. thank you for helping make LUYA better.

**Comment by nandes2062** [comment]
Thanks @nadar , good to know, my best wishes with the new interface, greetings

**Comment by nadar** [comment]
@nandes2062 i hope you will test the new interface, and give us feedback!
