### ISSUE TITLE
Controller of ngRest admin need more flexible

### ISSUE THREAD

**Issue by vuongminh** [luyadev/luya#1280]
I need to add some button to view file like `generate csv` button to do some custom action and i want to copy a view `crud.php` and modify it but after modify i don't know how to replace it when a `RenderCrud` make not through config. I suggest to create an objects `RenderCrud`, `NgRest` of \admin\ngrest\base\Controller through config to setup custom view file or any property in them.

**Comment by nadar** [comment]
Good idea to allow custom buttons. The only thing i thinkg about is how the design should look like when someone add's several buttons?

**Comment by vuongminh** [comment]
Maybe use some event to support developer attach code to view?

**EVENT_BEFORE_RENDER_GRID
   EVENT_AFTER_RENDER_GRID**

```php
on(EVENT_AFTER_RENDER_GRID, function($event) {
$event->result .= $view->renderPartial('myView');

});
```

**Comment by nadar** [comment]
or a configuration array like this?

```php
public $buttons = [
    ['label' => 'My Button', 'class' => 'btn btn-danger', 'href' => '#', 'ng-href' => 'angularFunction()'
];
```

**Comment by vuongminh** [comment]
I think your solution is good and simple.

**Comment by nadar** [comment]
@vuongminh I have not forget your request, we are just preparing an optimized admin ui. therefore i will integrate those new button ability

**Comment by nadar** [comment]
@vuongminh The basic version of such a feature is implemented, see https://luya.io/api/luya-admin-ngrest-base-Controller#$globalButtons-detail therfore i am going to close this issue. I am pretty sure we should the transform this into an object based context where you can define a button as a class which extends BaseGlobalButton or something.

But for now i am going to close this, please see what you can do with, otherwise just create a new issue. thank you!
