### ISSUE TITLE
Suggestion: Shorten and clearify main nav captions

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1428]
Because we have a left sidebar navigation and its more pretty to use short captions i suggest to rename them:

![image](https://user-images.githubusercontent.com/15183757/29944482-f2643964-8e9d-11e7-91d1-f2b62fbdf5a7.png)

In englisch too.

**Comment by nadar** [comment]
@dev7ch good idea. What about english suggestions?

**Comment by rolandschaub** [comment]
Dateien = Files
Inhalte = Contents
Einstellungen = Settings
Aktualisieren = Reload
Aktivität = Activities

Personally I prefer `Pages` or `Pages & Contents` (`Seiten` or `Seiten & Inhalte`) instead of `Contents`. And I think `Activities` is misleading as it displays users that are or were online (the dashboards show the activities). Maybe `Active Users` (`Aktive Benutzer`) would be more appropriate.

**Comment by nadar** [comment]
@rolandschaub i agree with u, lets take Pages (Seiten) instead of Contents. @dev7ch are u going to make a PR?

**Comment by dev7ch** [comment]
yes, i ll do.

- Files
- Pages
- Settings
- Reload
- Aktive Users *

* it would be great to have only one word here.

Whats about "Users" instead of "Aktive Users" ?

**Comment by nadar** [comment]
"Users" suggests the ability to change/add/modify users in general, which is not true.

Maybe just "Online" ?

**Comment by rolandschaub** [comment]
Its `Active` with a `c`, not a `k`. I think `Active Users` is more accurate as it doesn't display all users but only those that are or were previously active at the moment.

**Comment by nadar** [comment]
Ok, lets take `Active Users`

**Comment by dev7ch** [comment]
ok, thanks for your precision.
