### ISSUE TITLE
Question: Can we reduce admin mobile nav breakpoint?

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya#1437]
If I work with a 15" macbook and open the "inspect element" toolbar the left mainnav turns into the mobile nav.

I think ist to early.

Now we have `$mobile-nav-breakpoint: 1200px;`

Can we safely reduce this width? to 960px perhaps?

**Comment by nadar** [comment]
@dev7ch yes, i experience similar behaviors, event without the debug toolbar. Reduce to 960 would be good. Could you please send a PR?

**Comment by dev7ch** [comment]
yes, but i would like to mention to discuss with @TheMaaarc about it

**Comment by TheMaaarc** [comment]
@dev7ch I think 960 might be a good breakpoint, just test it properly with the CRUD.

We also have some problems with the cmsadmin on the "mobile" view. The blockholder on the right isn't fixed anymore (because it can't be) and you scroll sometimes the page and sometimes just the cmsadmin content – that needs some improvements too.

**Comment by nadar** [comment]
@TheMaaarc Maybe we should hide the block holder on mobile devices anyhow - in the next relase we could then bring up a mobile friendly block/insert/drag/drop solution.

**Comment by TheMaaarc** [comment]
@nadar Sounds good.

Or just a [+] sign at every place you could drop a block and then the blockholder as overlay. So you don't have to drag'n'drop.

**Comment by nadar** [comment]
Yes this is a good solution, i am going to make an issue for the next release, but for this one just hide the block holder on mobile.

@dev7ch please make a PR for the hide-on-mobile and changing the breakpoint.
