### ISSUE TITLE
Error install project

### ISSUE THREAD

**Issue by gorets** [luyadev/luya#1694]
![cmd 2017-12-02 14 11 23](https://user-images.githubusercontent.com/419682/33514772-d4f41f8c-d76a-11e7-9aff-5bfe5f6d7abf.png)

**Comment by nadar** [comment]
its running on windows? could you run with verbose on? `composer install --verbose`

**Comment by JohnnyMcWeed** [comment]
just go with another `composer update` and it should fix everything.. ;)
(at least in my case it did so)

**Comment by nadar** [comment]
As luya is installed along with luya composer plugin, this could cause the problem. So i would like to see the whole composer message (enable with --verbose).

Possible source which could cause this problem on luya composer plugin: https://github.com/luyadev/luya-composer/blob/master/src/Plugin.php#L58

**Comment by JohnnyMcWeed** [comment]
@gorets What happens if you use your server as admin, as mentioned in other applications with the same error? What happens if you use `composer update` after the error? Does it fix it?
@nadar Probably a permission problem as other people in other applications are facing similar problems, e.g. see here: https://github.com/vova07/yii2-start/issues/81 

>  tkdb commented on 13 May 2014 
Alternatively just allow your user-account to create  symbolic links, by default only Administrators group is allowed this but  local security policy configuration can be changed for that, see: http://php.net/symlink#109607  (from https://github.com/EcomDev/EcomDev_PHPUnit/issues/160)

**Comment by nadar** [comment]
@JohnnyMcWeed Yes, so we could just hide the error messages with `@symlink`, as its not a mandatory feature.

**Comment by gorets** [comment]
Run OpenServer as Admin, install is compleate 
` - Installing yiisoft/yii2-debug (2.0.12): Loading from cache
phpmailer/phpmailer suggests installing league/oauth2-google (Needed for Google XOAUTH2 authentication)
imagine/imagine suggests installing ext-imagick (to use the Imagick implementation)
imagine/imagine suggests installing ext-gmagick (to use the Gmagick implementation)
Writing lock file
Generating autoload files
> yii\composer\Installer::postCreateProject
chmod('public_html/assets', 0777)...done.
chmod('public_html/storage', 0777)...done.
chmod('runtime', 0777)...done.`

next spep: copy config files is ok.
next: launched the site and saw an error
![bug2](https://user-images.githubusercontent.com/419682/33517177-67fbdafc-d790-11e7-81f3-83702a393cf9.png)

**Comment by nadar** [comment]
@gorets This is a bug on windows systems in RC4, please install the dev-master or wait 10 days until the first stable relase 1.0.0 (hurray!).

Thanks for your report anyhow

**Comment by nadar** [comment]
Or if you just want to test very quickly on can also go into the vendor/luyadev/luya-core/traits

ApplicationTrait.php => getPackageInstaller()

change to: 

$file = Yii::getAlias('@vendor/luyadev/installer.php');

**Comment by nadar** [comment]
@gorets could you please try again the first steps? I pushed a fix to the luya composer repo. Thanks
