### ISSUE TITLE
Own variable type

### ISSUE THREAD

**Issue by liberosoft** [luyadev/luya#1864]
Hi,
Is there a way to create own variable type for a custom block? For example I'd like to add fckeditor plugin as a variable type, just like wysiwyg type.

Thanks

**Comment by nadar** [comment]
@liberosoft i just added a small guide example in how to add a custom type. In general: 

1. Its more recommend to create an issue about missing types, so everyone will profit.
2. But FKEDITOR add other wysiwyg is something we will never support as it just makes no sense in the block editors. 
3. Instead of using WYSIWG editor, you should use blocks, and create the structured input with heading, text, table etc. blocks. This is what its built for.

**Comment by liberosoft** [comment]
@nadar Thank you very much for your answer. I know that using FCK like editors isn't a good way, but  our client has the last word. They have used such editors in previous systems and won't change a way of thinking :)

Again, thank you very much, great work!

**Comment by nadar** [comment]
there is a very basic wysiwyg editor, maybe use this one? Whats the benefit of using FCK if you are not able to upload images and files? :-)

BUT: if you do a luya extension - which is public to everyone, i will contribute to this module if you need help.

**Comment by liberosoft** [comment]
There are some basic functionalities I can't find in this wysiwyg editor, like:
- text align
- text color
- image align

**Comment by nadar** [comment]
no, they are fixed defined here: https://github.com/luyadev/luya-module-cms/blob/master/src/frontend/commands/BlockController.php#L124-L180
