### ISSUE TITLE
Docker image for luya

### ISSUE THREAD

**Issue by pironmind** [luyadev/luya#1985]
Hello, can you provide somewhere luyadev/luya-docker-nginx image and config file which used for Nginx?

**Comment by nadar** [comment]
hi @pironmind, i am not sure what you mean. here you can see the docker image (https://github.com/luyadev/luya-docker-nginx) and the nginx config which is used by default: https://github.com/luyadev/luya-docker-nginx/blob/master/site.conf

The luya kickstarter already uses that image for development, the docker file is not yet meant for production:

+ https://github.com/luyadev/luya-kickstarter
+ docker compose file: https://github.com/luyadev/luya-kickstarter/blob/master/docker-compose.yml

**Comment by nadar** [comment]
I am going to close this issue because:

- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our slack team: slack.luya.io. We try to keep our issue tracker as clean as possible in order to focus on active issues.
