### ISSUE TITLE
different ip address instead of local host

### ISSUE THREAD

**Issue by sree-kumar** [luyadev/luya#1988]
### What steps will reproduce the problem?
Install `luya-kickstarter` in another intranet ip say `192.168.x.x`. Access the site using
http://192.168.2.x.x/luya-kickstarter/public_html/
Front page dispaly. Click the `admin` link
Page *404 Not found* Error comes.

### What is the expected result?
*Admin Console* must open.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
404 has nothing to do with this i would say. this is a wrong configured webserver problem i would say.  please provide more informations about webserver. maybe a screenshot will show whether the 404 is rendered trough yii or not.

**Comment by nadar** [comment]
I am going to close this issue because:

- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our slack team: slack.luya.io. We try to keep our issue tracker as clean as possible in order to focus on active issues.
