### ISSUE TITLE
Idea: Live theme editor

### ISSUE THREAD

**Issue by testt23** [luyadev/luya#2022]
#Is it expected to make a plugin that will serve to change the design live?  it's convenient. or if you don't expect any guidance on what can be integrated as an option, i would try

**Comment by nadar** [comment]
Hi @testt23 

that sounds interesting, but i am not sure to understand what you mean. You can switch the theme in the admin interface.

https://luya.io/guide/app-themes => see section "import and activate"

Does that help?

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.
