### ISSUE TITLE
JsonLD naming in the docs

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya#2033]
### What steps will reproduce the problem?
Checking the [JsonLd Luya docs](https://luya.io/guide/app-jsonld) I saw that it is talking about Value Types. 

### What is the expected result?
Coming from the [schema.org list view](https://schema.org/docs/full.html) I'd suggest stating that this means all those declared as [Data Types](https://schema.org/docs/full.html#datatype_tree). I think this naming should be followed.

Moreover they are instances of [`DataType`](https://schema.org/DataType). This means, that the current `BaseValue` class should be changed aswell to follow the hierarchy of schema.org.

So:
`BaseValue` should be renamed to `BaseDataType` (as compared to the `BaseThing`)
Then there is a `DataType`
And then there are the data types...

**Comment by nadar** [comment]
ValueTypes are only used to ensure people provide an URL or E-Mail or any other special value. This allows us to validate the user input. I would just keep those `...Values` classes as it has nothing to do with Schema.

**Comment by JohnnyMcWeed** [comment]
So what's the point in not going for the default schema data types, which are explicitly for that?

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.
