### ISSUE TITLE
Theme layout override mechanism

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya#2036]
When having a main CMS layout (app/views/cmslayouts/main.php) and then inside the theme adding a main layout (app/themes/themename/views/cmslayouts/main.php) I think that this should override the app's main layout.

### What steps will reproduce the problem?
Add a main cms layout to the theme (app/themes/themename/views/cmslayouts/main.php)

### What is the expected result?
Overriding the default main layout (app/views/cmslayouts/main.php)

### What do you get instead?
No layout update -> still using the default main layout (app/views/cmslayouts/main.php)

**Comment by nadar** [comment]
@boehsermoe maybe you can help here?

**Comment by boehsermoe** [comment]
The app views will never be override from a theme. At first it will check the app views, than theme views, than parent theme views, than that parent, ...

But especially for the cms layout you have to choose those one in the admin ui wich layout u will use for a page. Maybe this we should document it better. 

It is hard to erase this step with the cms layout, because the layout ID are stored in the database. And after theme activating we would update all page layouts.

**Comment by nadar** [comment]
Thank you @boehsermoe for the detailed explanation. Yes, maybe some documentation would be nice regarding this.
