### ISSUE TITLE
Wrong namespace in story theme

### ISSUE THREAD

**Issue by hbugdoll** [luyadev/luya#2155]
There is a wrong namespace in asset file and view file of the recently added **story theme** for use with the `luya-themes` module.

Furthermore, it would be nice to have some clues in the readme about the different directory structure of this theme (obviously created by console command `luya theme/create`).

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [LUYA discussions](https://github.com/luyadev/luya/discussions))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our discussion: [LUYA discussions](https://github.com/luyadev/luya/discussions). We try to keep our issue tracker as clean as possible in order to focus on active issues.
