### ISSUE TITLE
Show users location

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya#626]
Is it possible to show the users "location" in the "Users online" screen?

**Comment by nadar** [comment]
This issue is open for a long time, so i made a quick review:

When a request to **any** API happens, the UserOnline model is updatet with the path of the request, so when luya is loading a few different requests are made:

-> api-admin-storage
-> api-admin-common
-> api-admin-menu
etc.

which are not "real" locations you can display to the user, its just a call to an api which let the system know the last route requested and refresh its user-online state (request made 1min ago).

In order to store "usable" location informations we would need to differ from "interesting" and "not interesting" request.

The implementation of such a feature should also include the "lock state" of the requested url to other users (when an ngrest item is edited, other users can't edit, when a cms page is in edit mode, other user's can not edit too).
