### ISSUE TITLE
database migrate 

### ISSUE THREAD

**Issue by rahulk-k** [luyadev/luya#816]
Im getting error while using ./vendor/bin/luya migrate command in windows xampp server
![error](https://cloud.githubusercontent.com/assets/10880236/14165811/bf3a0a16-f72a-11e5-8827-0d5528262b1f.PNG)

**Comment by nadar** [comment]
You have to use the "windows-command approach", going into `public_html` and run commands like this `php index.php <command>` this has been added to the new docs already, but not published on luya.io as the docs will be updated due to new releases.

https://github.com/luyadev/luya/blob/master/docs/guide/en/install-windows.md (thanks to @mootensai)

**Comment by nadar** [comment]
I have also found out that all bin files can be runned with `exec` command of composer, so instead of

```
./vendor/bin/luya migrate
```

you can run on windows (with composer installed)

```
composer exec migrate
```

in the kickstarter directory.

**Comment by nadar** [comment]
@rahulk-k can we close this issue?
