### ISSUE TITLE
CMS admin Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by lookagit** [luyadev/luya#981]
## What steps will reproduce the problem?

navigate to http://localhost/luya-kickstarter/public_html/admin results yii\base\ErrorException
![image](https://cloud.githubusercontent.com/assets/17603638/18293654/8a1fdc74-7494-11e6-99c3-0b5685bc0114.png)
### Additional infos

| Q | A |
| --- | --- |
| LUYA Version | 1.0.0 |
| PHP Version | 5.6.23 |
| Platform | XAMPP |
| Operating system | Windows/ |

**Comment by nadar** [comment]
Hi @lookagit 

What happens if you reload the admin interface again? I think it can not copy/wirte the asset files into your assets folder.

Could you make sure the following folders are writeable (mabye just changed to 0777 permissions):

+ /runtime
+ /public_html/assets
+ /public_html/storage

In addition maybe run the `health` command (`composer exec luya health`) if not already done.

Another option would also be to try enabling the [linkAssets](http://www.yiiframework.com/doc-2.0/yii-web-assetmanager.html#$linkAssets-detail) options of the asset Manager (in the components section) in your config, but i am not sure if this is going to work on windows:

```php
'assetManager' => [
    'class' => 'luya\web\AssetManager',
    'linkAssets' => true,
],
```

**Comment by nadar** [comment]
Does the problem still appears @lookagit or can we close this issue?

**Comment by nadar** [comment]
I am going to close this as there are no more informations. Feel free to create a new issue, when you got more or another problem.
